per_listener_settings false

listener 1884
allow_anonymous false

persistence true
persistence_location C:\custom_secure_mqtt_broker\secure-mqtt-broker\data\
log_dest file C:\custom_secure_mqtt_broker\secure-mqtt-broker\logs\mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true

plugin C:\Program Files\mosquitto\mosquitto_dynamic_security.dll
plugin_opt_config_file C:\custom_secure_mqtt_broker\secure-mqtt-broker\dynamic-security.json
