per_listener_settings true
listener 1883
allow_anonymous true
listener 8883
allow_anonymous false

cafile C:\custom_mqtt_broker\certificates\ca.crt
certfile C:\custom_mqtt_broker\certificates\broker.crt
keyfile C:\custom_mqtt_broker\certificates\broker.key

require_certificate true
use_identity_as_username false

persistence true
persistence_location C:\custom_mqtt_broker\secure-mqtt-broker\data\

log_dest file C:\custom_mqtt_broker\secure-mqtt-broker\logs\mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true

plugin C:\Program Files\mosquitto\mosquitto_dynamic_security.dll
plugin_opt_config_file C:\custom_mqtt_broker\secure-mqtt-broker\dynamic-security.json